# Generated by Django 3.0.7 on 2020-06-29 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_start_date', models.DateField()),
                ('exam_end_date', models.DateField()),
                ('exam_duration', models.DurationField()),
                ('full_mark', models.PositiveIntegerField()),
                ('pass_number', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField(default=2020)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='classes.ClassYearInfo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_routine', to='exam.Exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_routine', to='classes.SubjectList')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam', to='exam.ExamTypes'),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('marks', models.PositiveSmallIntegerField()),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.ClassYearInfo')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Sections')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.SubjectList')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_test', to='account.Teacher')),
            ],
        ),
    ]
