# Generated by Django 3.0.7 on 2020-06-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200629_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='joined_at',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('staff', 'Staff'), ('gardian', 'Gardian')], max_length=7),
        ),
        migrations.AlterField(
            model_name='student',
            name='gardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to='account.Gardian'),
        ),
    ]
