# Generated by Django 3.0.7 on 2020-07-03 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_leaveinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
