# Generated by Django 3.0.7 on 2020-07-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200703_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
