# Generated by Django 3.0.7 on 2020-07-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200703_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveinfo',
            name='is_left',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
