# Generated by Django 3.0.7 on 2020-07-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200704_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='account.Gardian'),
        ),
    ]
