# Generated by Django 3.0.7 on 2020-07-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200704_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveinfo',
            old_name='discription',
            new_name='description',
        ),
    ]
