# Generated by Django 3.0.7 on 2020-07-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200705_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='account.Gardian'),
        ),
    ]
