# Generated by Django 3.0.7 on 2020-07-08 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200705_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='guardian_personal_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=7, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='gardian',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('staff', 'Staff'), ('guardian', 'Guardian')], max_length=8),
        ),
        migrations.DeleteModel(
            name='Gardian',
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='account.Guardian'),
        ),
    ]
