# Generated by Django 3.0.7 on 2020-06-29 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='account.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPerClassAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance', to='classes.ClassYearInfo')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance', to='classes.Sections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance', to='account.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_attendance', to='classes.SubjectList')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='classes.ClassYearInfo')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance', to='classes.Sections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='account.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_day_class', models.SmallIntegerField()),
                ('class_start_time', models.TimeField()),
                ('class_end_time', models.TimeField()),
                ('break_start_time', models.TimeField(blank=True, null=True)),
                ('break_duration', models.DurationField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(default=2020)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='classes.ClassYearInfo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='routine_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='routine_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sat', 'Sat'), ('Sun', 'Sun'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_routine', to='routine.Routine')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_routine', to='classes.Sections')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_routine', to='classes.SubjectList')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_routine', to='account.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ClassHappend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_proxy', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_happend', to='classes.ClassYearInfo')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_happend', to='classes.Sections')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_happend', to='classes.SubjectList')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_taken', to='account.Teacher')),
            ],
        ),
    ]
