# Generated by Django 3.0.7 on 2020-06-25 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_day_class', models.SmallIntegerField()),
                ('class_start_time', models.TimeField()),
                ('class_end_time', models.TimeField()),
                ('break_start_time', models.TimeField()),
                ('break_duration', models.DurationField()),
                ('year', models.IntegerField(default=2020)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('_created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='routine_created', to=settings.AUTH_USER_MODEL)),
                ('_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='routine_updated', to=settings.AUTH_USER_MODEL)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='classes.ClassYearInfo')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sat', 'Sat'), ('Sun', 'Sun'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_routine', to='routine.Routines')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_routine', to='classes.Sections')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_routine', to='classes.SubjectList')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_routine', to='account.Teacher')),
            ],
        ),
    ]
