# Generated by Django 3.0.7 on 2020-07-05 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200705_2303'),
        ('classes', '0004_auto_20200705_2311'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classhappend',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_happend', to='classes.Sections'),
        ),
        migrations.AlterField(
            model_name='classhappend',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_happend', to='classes.SubjectList'),
        ),
        migrations.AlterField(
            model_name='classhappend',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_taken', to='account.Teacher'),
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_routine', to='classes.SubjectList'),
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_routine', to='account.Teacher'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routine',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='classes.Sections'),
        ),
        migrations.AlterField(
            model_name='studentperclassattendance',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_attendance', to='classes.SubjectList'),
        ),
    ]
