# Generated by Django 3.0.7 on 2020-06-27 05:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classyear_attendance_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassHappend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_proxy', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date(2020, 6, 27))),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_happend', to='classes.ClassYearInfo')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_happend', to='classes.Sections')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_happend', to='classes.SubjectList')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_taken', to='account.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_day_class', models.SmallIntegerField()),
                ('class_start_time', models.TimeField()),
                ('class_end_time', models.TimeField()),
                ('break_start_time', models.TimeField()),
                ('break_duration', models.DurationField()),
                ('year', models.PositiveIntegerField(default=2020)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='classes.ClassYearInfo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='routine_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='routine_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2020, 6, 27))),
                ('is_present', models.BooleanField(default=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='classes.ClassYearInfo')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance', to='classes.Sections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='account.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPerClassAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2020, 6, 27))),
                ('is_present', models.BooleanField(default=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance', to='classes.ClassYearInfo')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance', to='classes.Sections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance', to='account.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_attendance', to='classes.SubjectList')),
            ],
        ),
        migrations.RenameModel(
            old_name='RoutineDetails',
            new_name='ClassRoutine',
        ),
        migrations.DeleteModel(
            name='Routines',
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_routine', to='routine.Routine'),
        ),
    ]
