# Generated by Django 3.0.7 on 2020-06-27 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_auto_20200627_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classhappend',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentperclassattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
