# Generated by Django 3.0.7 on 2020-06-29 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('code', models.CharField(choices=[('i', 'i'), ('ii', 'ii'), ('iii', 'iii'), ('iv', 'iv'), ('v', 'v'), ('vi', 'vi'), ('vii', 'vii'), ('viii', 'viii'), ('ix', 'ix'), ('x', 'x'), ('xi', 'xi'), ('xii', 'xii')], max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_group', models.BooleanField(default=False)),
                ('attendance_type', models.CharField(choices=[('per day', 'Per Day'), ('per class', 'Per Class')], default='per day', max_length=10)),
                ('year', models.IntegerField(default=2020)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_year', to='classes.ClassList')),
            ],
        ),
        migrations.CreateModel(
            name='ClassYearInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='classes.ClassYear')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='classes.ClassYearInfo')),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='account.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('discription', models.TextField(blank=True, null=True)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('terget_class', models.ManyToManyField(related_name='subject_list', to='classes.ClassList')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takes', models.ManyToManyField(related_name='takes', to='classes.SubjectList')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('session', models.IntegerField(default=2020)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='classes.ClassYear')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='classes.Groups')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='classes.Sections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info', to='account.Student')),
            ],
        ),
        migrations.AddField(
            model_name='classyearinfo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_year', to='classes.Groups'),
        ),
        migrations.AddField(
            model_name='classyearinfo',
            name='subjects',
            field=models.ManyToManyField(related_name='class_year', to='classes.SubjectList'),
        ),
        migrations.AddField(
            model_name='classyear',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_year', to='classes.Shifts'),
        ),
    ]
