# Generated by Django 3.0.7 on 2020-07-03 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200703_1229'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAcademicInfo',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='academic_info', serialize=False, to='account.Teacher')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('takes', models.ManyToManyField(related_name='takes', to='classes.SubjectList')),
            ],
        ),
        migrations.AlterField(
            model_name='sections',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='account.Teacher'),
        ),
        migrations.AlterField(
            model_name='studentacademicinfo',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='classes.ClassYear'),
        ),
        migrations.AlterField(
            model_name='studentacademicinfo',
            name='roll',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentacademicinfo',
            name='section',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
