# Generated by Django 3.0.7 on 2020-06-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classyear',
            name='attendance_type',
            field=models.CharField(choices=[('per day', 'Per Day'), ('per class', 'Per Class')], default='per day', max_length=10),
        ),
    ]
