# Generated by Django 3.0.7 on 2020-07-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200704_1247'),
        ('classes', '0002_auto_20200703_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAcademicInfo',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='academic_info', serialize=False, to='account.Staff')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherSubjectInfo',
        ),
    ]
