# Generated by Django 3.0.7 on 2020-07-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200705_2303'),
        ('classes', '0003_auto_20200704_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classyearinfo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_year', to='classes.Groups'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='account.Teacher'),
        ),
        migrations.AlterField(
            model_name='studentacademicinfo',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.ClassYear'),
        ),
        migrations.AlterField(
            model_name='studentacademicinfo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.Groups'),
        ),
    ]
